name: Deploy Tomcat
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install AWS CLI
      run: sudo apt-get install -y awscli
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_EC2_REGION }}
    - name: Start EC2 Instance
      run: |
        aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
        aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
    - name: Install Tomcat
      env:
        EC2_USER: ubuntu
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > snekha.pem
        chmod 400 snekha.pem
        ssh -o StrictHostKeyChecking=no -i snekha.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          sudo yum install tomcat
          sudo yum install tomcat-webapps tomcat-admin-webapps tomcat-docs-webapp tomcat-javadoc
          sudo systemctl start tomcat
          sudo systemctl enable tomcat
          sudo systemctl restart tomcat
        EOF